@host = https://localhost:7000

### Register Student
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "firstName": "Ahmed",
  "lastName": "Ali",
  "phoneNumber": "01012345678",
  "email": "ahmed@gmail.com",
  "password": "Ahmed@123",
  "role": "Student"
}